# Generated by Django 4.0.4 on 2022-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('rating', models.CharField(max_length=3, verbose_name='Rating')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Description')),
                ('director', models.CharField(default='', max_length=30, verbose_name='Director')),
                ('image_url', models.TextField(max_length=250, verbose_name='Image')),
                ('imdb_url', models.TextField(max_length=250, verbose_name='Imdb')),
                ('rezka_url', models.TextField(max_length=250, verbose_name='Hdrezka')),
            ],
        ),
    ]
